### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by anes66** [SaltyGrandpa/salty_death#1]
when you go atl+f4 when dead it sets from 1 to 0 and you are live again is it possible to fix this?

**Comment by SaltyGrandpa** [comment]
What other add ons are you using? This is likely a conflicting add on, I'd suspect a skin related mod.

**Comment by anes66** [comment]
`start es_extended
start esx_menu_default
start esx_menu_list
start esx_menu_dialog
start esx_boilerplate
start esx_billing
start esx_identity
start esx_society
start esx_addonaccount
start esx_addoninventory
start esx_datastore
start esx_phone3
start esx_blackberry
start esx_policejob
start esx_drugs
start esx_holdup
# start esx_skin
start esx_status
start esx_basicneeds
start esx_eden_garage
start esx_vehicleshop
start esx_ambulancejob
start esx_accessories
start esx_license
start esx_weashops
start esx_lscustom
start esx_mecanojob
start esx_property
start esx_jobs
start esx_rpchat
start esx_animations
start esx_dmvschool
start esx_joblisting
start esx_taxijob
start esx_bankerjob
start esx_realestateagentjob
start esx_shops
start esx_service
start esx_AdvancedFuel
start esx_holdupbank
start esx_borrmaskin
start esx_tattoosShops
start esx_slotmachine
start esx_voice
start esx_phone3
start esx_clotheshop
start esx_rpchat
start esx_advanced_inventory
start esx_grove
start esx_pranjepara
start esx_optionalneeds
start esx_unicornjob
start esx_unishow`

i dont know if that maybe can help you

**Comment by SaltyGrandpa** [comment]
Can you try without: esx_skin, esx_accessories, esx_borrmaskin, esx_tattosShop ? Those look like the skin related mods.

**Comment by anes66** [comment]
I can test it for you on my test server but these resources are needed for my roleplay server and if you wish i can write what is happening and add 1 by 1 resource so we know exact what is making problem
